config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts, only: [:index, :show, :new, :create] do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    raise
    @post = Post.create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectTrial2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <div class="container">
        <p> <%= link_to "Create a new post", new_post_path %> </p>
      </div>
    </div>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1 class="mb-3">TODAY'S POSTS</h1>

<% @posts.each do |post| %>
  <h2> <%= link_to post.name, post_path(post) %> </h2>
  <p> <%= post.description %> </p>
  <p> <%= post.duration %> </p>
<% end %>

app/views/posts/new.html.erb
<%= simple_form_for @post do |p| %>
  <%= p.input :name %>
  <%= p.input :description %>
  <%= p.input :duration %>
  <%= p.input :photo %>
  <%= p.input :photo_cache, as: :hidden %>
  <%= p.submit %>
<% end %>

app/views/posts/show.html.erb
<h2> <%= @post.name %> </h2>
<p> <%= @post.description %> </p>
<p> <%= @post.duration %> minutes</p>